# Generated by Django 4.2.4 on 2023-08-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.CharField(blank=True, max_length=200, null=True)),
                ('tensile_strength', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('young_modulus', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
            ],
            options={
                'verbose_name': 'Purpose',
                'verbose_name_plural': 'Purposes',
            },
        ),
    ]
