# Generated by Django 4.2.4 on 2023-08-21 08:26

import composite.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purpose', '0001_initial'),
        ('matrix', '0001_initial'),
        ('fibre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_tensile_strength', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('desired_young_modulus', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('fibre_percentage_against_tensile_strength', models.ImageField(blank=True, null=True, upload_to=composite.models.get_upload_path)),
                ('matrix_percentage_against_tensile_strength', models.ImageField(blank=True, null=True, upload_to=composite.models.get_upload_path)),
                ('fibre_percentage_against_young_modulus', models.ImageField(blank=True, null=True, upload_to=composite.models.get_upload_path)),
                ('matrix_percentage_against_young_modulus', models.ImageField(blank=True, null=True, upload_to=composite.models.get_upload_path)),
                ('fibre_percentage_against_tensile_strength_young_modulus', models.ImageField(blank=True, null=True, upload_to=composite.models.get_upload_path)),
                ('matrix_percentage_against_tensile_strength_young_modulus', models.ImageField(blank=True, null=True, upload_to=composite.models.get_upload_path)),
                ('fibre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fibre', to='fibre.fibre')),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matrix', to='matrix.matrix')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purpose', to='purpose.purpose')),
            ],
        ),
    ]
