# Generated by Django 4.2.4 on 2023-08-21 09:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('composite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='composite',
            old_name='desired_tensile_strength',
            new_name='best_tensile_strength',
        ),
        migrations.RenameField(
            model_name='composite',
            old_name='desired_young_modulus',
            new_name='best_young_modulus',
        ),
        migrations.AddField(
            model_name='composite',
            name='best_fibre_percentage',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='composite',
            name='best_matrix_percentage',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='composite',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='composite',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
