# Generated by Django 4.2.4 on 2023-08-22 07:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('composite', '0002_rename_desired_tensile_strength_composite_best_tensile_strength_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='composite',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='composite',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='composite',
            name='best_fibre_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='composite',
            name='best_matrix_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='composite',
            name='best_tensile_strength',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='composite',
            name='best_young_modulus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='composite',
            index=models.Index(fields=['-id'], name='composite_c_id_efbe6c_idx'),
        ),
    ]
